PATH="$HOME/junest/bin:$PATH"
PATH="/usr/lib64/openmpi/bin:$PATH"
PATH="/usr/local/krb5/bin:/usr/local/ossh/bin:$PATH"
PATH="$HOME/anaconda3/bin:$PATH"
export PATH="$HOME/bin:$HOME/.local/bin:$PATH:/opt/anaconda/bin"
export LD_LIBRARY_PATH="/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH"
export EDITOR="emacsclient"
export LESS=-RX
export KRB5_CONFIG=/usr/local/krb5/etc/krb5.conf
